from distutils.core import setup

setup(
name='CoalescentTree',
version='0.0.8',
description='Tools for handling haploid coalescent trees generated by SLiM',
author='Marie Temple-Boyer',
author_email='marie.temple-boyer@eleves.enpc.fr',
packages=['coalescent_tree', 'compare_theory']
)
